"""
updater.py - Auto-update module for claude-usage CLI.

Checks the GitHub API for the latest release, downloads the appropriate
binary for the user's operating system, and performs an in-place swap.
Only runs when the application is packaged as a PyInstaller executable.

Update flow:
  1. Query GitHub Releases API for latest tag
  2. Compare against CURRENT_VERSION
  3. Download the OS-appropriate asset
  4. Swap the running executable in-place
"""

import urllib.request
import json
import sys
import os
import platform

# IMPORTANT: Update this whenever you push a new release
CURRENT_VERSION = "1.0.1"
GITHUB_REPO = "DEADSERPENT/claude-usage"


def check_for_updates():
    """Check GitHub for a newer release and auto-update if available."""
    try:
        url = f"https://api.github.com/repos/{GITHUB_REPO}/releases/latest"
        req = urllib.request.Request(url, headers={'User-Agent': 'claude-usage-cli'})
        with urllib.request.urlopen(req, timeout=5) as response:
            data = json.loads(response.read().decode())

        latest_version = data["tag_name"].lstrip('v')

        if latest_version > CURRENT_VERSION:
            print(f"\n[!] New version v{latest_version} available! (Current: v{CURRENT_VERSION})")
            print("Downloading update...")
            download_and_update(data)
    except Exception:
        # Fail silently if offline or API rate limited
        pass


def download_and_update(release_data):
    """Download the latest binary and swap it with the running executable."""
    system = platform.system().lower()

    # Map OS to the asset names generated by GitHub Actions
    if system == "windows":
        asset_name = "claude-usage-windows.exe"
    elif system == "darwin":
        asset_name = "claude-usage-macos"
    else:
        asset_name = "claude-usage-linux"

    download_url = None
    for asset in release_data.get("assets", []):
        if asset["name"] == asset_name:
            download_url = asset["browser_download_url"]
            break

    if not download_url:
        print("Update failed: No suitable binary found for your OS.")
        return

    current_exe = sys.executable
    new_exe_path = current_exe + ".new"

    # Download the new binary
    urllib.request.urlretrieve(download_url, new_exe_path)

    # Swap the binaries
    if system == "windows":
        old_exe = current_exe + ".old"
        if os.path.exists(old_exe):
            try:
                os.remove(old_exe)
            except OSError:
                pass
        os.rename(current_exe, old_exe)
        os.rename(new_exe_path, current_exe)
    else:
        os.replace(new_exe_path, current_exe)
        os.chmod(current_exe, 0o755)

    print("Update complete! Please run the command again to use the new version.")
    sys.exit(0)
